### ISSUE TITLE
Include reference count in data export

### ISSUE THREAD

**Issue by winstonDeGreef** [oeis/oeis#19]
I need the reference count of each sequence. I have tried to calculate this myself, but get a slightly different number. Can this be included in the data export?
![image](https://github.com/oeis/oeis/assets/71840364/83ca31bf-d0f8-4cf3-9e5f-1f945f57120a)
(the number in the top right)

**Comment by winstonDeGreef** [comment]
as in the oeis/oeisdata repository

**Comment by rsc** [comment]
The ref count is derived data so I'd rather not include it in the oeisdata repository. To do the count you just count the number of sequences where the A number appears anywhere in the text. The ref counts on the web site can be slightly different because they are only updated periodically - about once a day per sequence.
