### ISSUE TITLE
perhaps something wrong on A222155 or A226858 ?

### ISSUE THREAD

**Issue by ghost** [oeis/oeis#21]
Dears,
Please read my repo about OEIS data.
I think perhaps some think is not exactly on A222155, A226858.

repo : manaranda/ABOUT-DATA-ON-SOME-OEIS-SEQUENCES
files: *_A222155.log, *_A226858.log

**Comment by hvds** [comment]
1) Such issues are normally better raised on the sequence itself or to the mailing list. I think issues here are intended to be about the software that runs the OEIS, rather than about the sequences themselves. (I will try to put together a README file to make that clearer.)

2) It is not clear to me what you think the issue is: are you suggesting that 287327040 should not be in A222155 because there are 5 matching sets rather than 4? I interpret the sequence definition to imply "there are at least four distinct triples" (not "exactly four"), so it seems to be correct that 287327040 is included.
